### ISSUE TITLE
Authoritative source for DocumentDB

### ISSUE THREAD

**Issue by rnagpal** [jcormont/documentdb-typescript#11]
I'm not familiar with typescripts but we have a customer who wants to have the authoritative source for DocumentDB. Can he just install your package and have it working?

Does that includes all APIs as in Node.js SDK Release 1.11.0?

Do you know who maintains https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/documentdb/index.d.ts  and if your version is more up-to-date, we should update the above?

Is there a tool to generate the .d.ts file from the nodejs source files of Node.js SDK or is this more of a manual work that you have done?

**Comment by jcormont** [comment]
Hi Rajesh. Surely the "authoritative source for DocumentDB" would be Microsoft, no? This library builds on the library provided by your team, and I am not affiliated with MS. Could you elaborate on what this customer needs?

This library is built on top of the Node.js SDK (written in JavaScript) but does not include it. It is referenced as an NPM dependency. Once this library is installed with NPM, the NPM CLI will automatically install and link the Node.js SDK.

As for the Type Definitions (.d.ts files), I know the version you linked to is pretty incomplete and out of date. My library includes its own .d.ts file for the Node.js SDK but is also incomplete (albeit slightly more up to date).

You can view a.d.ts file as a formal description of the API. But since this library builds on the Node.js SDK and extends the API in a more object-oriented way (closer to the .NET API), the .d.ts for this library itself is completely different and does not apply to the "vanilla" Node.js SDK. There is no tool to generate a .d.ts file from a library automatically, other than the TypeScript compiler -- which means the source must be valid TypeScript which exports its methods, variables etc. in a way that is compatible with TypeScript or at least ES6. The source for the Node.js SDK is clearly not written in this way.

Let me know if I can help any other way.
