### ISSUE TITLE
"Upserting document: undefined" when there's no "id" property

### ISSUE THREAD

**Issue by snobu** [jcormont/documentdb-typescript#2]
When i call 
```javascript
    let doc: any = await getJsonFromWebRequest(REST_ENDPOINT_URL);
    await coll.storeDocumentAsync(doc, StoreMode.Upsert);
```

this gets executed:
```
tryStore = (callback) => this.database.client.log(data.id ? "Upserting document: " + data.id : "Upserting document.")
```
([Context here](https://github.com/jcormont/documentdb-typescript/blob/dbe762caed2513f182c92dbd02f7794700572cae/src/Collection.ts#L183))

and because my JSON object has no `id` property, that ends up printing:
`Upserting document: undefined`

Should we probably change that to somethig like
```
tryStore = (callback) => this.database.client.log(data.id ? "Upserting document: " + data.id : "Upserting document.")
```
or am i missing something obvious and i'm _doing it wrong_?

**Comment by jcormont** [comment]
Thanks, I see what you mean.
Although your first quote should read:

```typescript
    tryStore = (callback) =>
        this.database.client.log("Upserting document: " + data.id) &&
        this.database.client.documentClient.upsertDocument(this._self,
            data, undefined, callback);
```

This doesn't consider the case where `data.id` is undefined, indeed, so it prints "Upserting document: undefined" (which actually isn't really wrong, since the document ID *is* undefined, but it doesn't look great).

To be clear, the underlying upsertDocument function will still generate a random ID so your code works as expected. Also if you know the ID is empty, you could force a different mode like `StoreMode.CreateOnly`, or generate your own ID which may be safer since random IDs may technically still clash with existing IDs. This would then result in overwriting the existing document in your case.

However I suppose we could add a check for this like you suggested, and print something like "Upserting document: (no ID)" to make it clear what's happening.

Feel free to submit a pull request, otherwise I'll add it in the next patch/minor version.
